#!/usr/bin/python

import argparse

import ivoxoar.space

if __name__ == "__main__":
    ivoxoar.space.silence_numpy_errors()

    parser = argparse.ArgumentParser(prog='ivoxinfo')
    parser.add_argument('infile', help='input file, must be a .zpi')

    args = parser.parse_args()
    
    space = ivoxoar.space.Space.fromfile(args.infile)
    print space
