#!/usr/bin/python

import sys
import os
import argparse
import numbers
import numpy
import matplotlib.pyplot as pyplot
import matplotlib.colors

import BINoculars.space, BINoculars.plot, BINoculars.fit, BINoculars.util

if __name__ == "__main__":
    BINoculars.space.silence_numpy_errors()

    parser = argparse.ArgumentParser(prog='ivoxplot')
    parser.add_argument('infile', nargs='+')
    BINoculars.util.argparse_common_arguments(parser, 'savepdf', 'savefile', 'clip', 'nolog', 'project', 'slice', 'pslice', 'subtract')
    parser.add_argument('--multi', default=None, choices=('grid', 'stack'))
    parser.add_argument('--fit', default = None)
    parser.add_argument('--guess', default = None)
    args = parser.parse_args()

    if args.subtract:
        subtrspace = BINoculars.space.Space.fromfile(args.subtract)
        subtrspace, subtrinfo = BINoculars.util.project_and_slice(subtrspace, args, auto3to2=True)
        args.nolog = True

    guess = []
    if args.guess is not None:
        for n in args.guess.split(','):
            guess.append(float(n.replace('m', '-')))

    # PLOTTING AND SIMPLEFITTING
    pyplot.figure(figsize=(12, 9))
    plotcount = len(args.infile)
    plotcolumns = int(numpy.ceil(numpy.sqrt(plotcount)))
    plotrows = int(numpy.ceil(float(plotcount) / plotcolumns))

    for i, filename in enumerate(args.infile):
        space = BINoculars.space.Space.fromfile(filename)
        space, info = BINoculars.util.project_and_slice(space, args, auto3to2=True)

        fitdata = None
        if args.fit:
            fit = BINoculars.fit.get_class_by_name(args.fit)(space, guess)
            print fit
            if fit.success:
                fitdata = fit.fitdata

        if plotcount > 1:
            if space.dimension == 1 and args.multi is None:
                args.multi = 'stack'
            if space.dimension == 2 and args.multi != 'grid':
                if args.multi is not None:
                    sys.stderr.write('warning: stack display not supported for multi-file-plotting, falling back to grid\n')
                args.multi = 'grid'
            # elif space.dimension == 3:
                # not reached, project_and_slice() guarantees that
            elif space.dimension > 3:
                sys.stderr.write('error: cannot display 4 or higher dimensional data, use --project or --slice to decrease dimensionality\n')
                sys.exit(1)

        if args.subtract:
            space -= subtrspace

        basename = os.path.splitext(os.path.basename(filename))[0]

        if args.multi == 'grid':
            pyplot.subplot(plotrows, plotcolumns, i+1)
        BINoculars.plot.plot(space, pyplot.gcf(), pyplot.gca(), label=basename, log=not args.nolog, clipping=float(args.clip), fit=fitdata)

        if plotcount == 1:
            pyplot.suptitle('{0} {1}'.format(basename, ' '.join(info)))
        elif args.multi == 'grid':
            pyplot.gca().set_title(basename)


    if plotcount > 1:
        pyplot.suptitle('{0} files, {1}'.format(plotcount, ' '.join(info)))
        if args.multi == 'stack':
            pyplot.legend()

    if args.savepdf or args.savefile:
        if args.savefile:
            pyplot.savefig(args.savefile)
            #print 'saved at {0}'.format(args.savefile)
        else:
            filename = '{0}_plot.pdf'.format(os.path.splitext(args.infile[0])[0])
            filename = BINoculars.util.find_unused_filename(filename)
            pyplot.savefig(filename)
            #print 'saved at {0}'.format(filename)
    else:
        pyplot.show()
